// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Project struct {
	Projectid int64
	Name      string
}

type Task struct {
	ID   int64
	Name string
}

type User struct {
	Userid int64
	Name   string
}
